project:
  type: website
  output-dir: docs
  render:
    - import-qc-metabarcoding.qmd
    - background.qmd
    - index.qmd
    - analysis-microcolonizers.qmd

website:
  title: "Microcolonizers"
  navbar:
    left:
      - href: background.qmd
        text: Home
      - href: index.qmd
        text: QIIME2 & Temperature logger analysis
      - href: import-qc-metabarcoding.qmd
        text: Preprocess & compile data
      - href: analysis-microcolonizers.qmd
        text: Data analysis & statistics

format:
  html:
    theme: pulse
    css: styles.css
    code-fold: false
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 2


